INSERT INTO OFFER_CATEGORY(IS_ACCEPTED, IS_ENABLED, DESCRIPTION, NAME) VALUES(true, true, 'Fun times', 'Music');
INSERT INTO AUTHENTIFIED_USER(EMAIL, NAME, IS_DELETED, DTYPE, PROVIDER_NAME) VALUES('gas@gmail.com', 'Petar', false, 'Provider',  'Gas Srbija');
INSERT INTO EVENT_TYPE(IS_ACTIVE, DESCRIPTION, NAME) VALUES(true, 'Ide gas', 'Rave')