INSERT INTO OFFER_CATEGORY(ID, IS_ACCEPTED, IS_ENABLED, DESCRIPTION, NAME) VALUES(1, true, true, 'Fun times', 'Music')

INSERT INTO AUTHENTIFIED_USER(ID, EMAIL, NAME, IS_DELETED, DTYPE, PROVIDER_NAME) VALUES(1, 'gas@gmail.com', 'Petar', false, 'Provider',  'Gas Srbija');